### Import packages

In [26]:
import pandas as pd 
import os
import sys

### Data Files

In [27]:
RAW_DATA_PATH = "../data/raw/HouseTS.csv"

### Setting Rows and Columns

In [28]:
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

### Convert data into dataframe

In [29]:
df = pd.read_csv(RAW_DATA_PATH)
df

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta
4,2012-07-31,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,2012,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,Atlanta-Sandy Springs-Alpharetta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884087,2023-08-31,438000.0,450000.0,313.553299,322.866706,185.0,189.0,227.0,132.0,20.0,0.979446,0.189189,0.476190,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,438238.668892,Tampa-St. Petersburg-Clearwater
884088,2023-09-30,449950.0,459900.0,314.024277,318.285714,192.0,189.0,243.0,170.0,18.0,0.975016,0.166667,0.460317,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,440569.503271,Tampa-St. Petersburg-Clearwater
884089,2023-10-31,450000.0,449450.0,312.328767,314.374076,187.0,192.0,264.0,185.0,21.5,0.971822,0.122995,0.416667,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,442965.899354,Tampa-St. Petersburg-Clearwater
884090,2023-11-30,470000.0,425000.0,312.328767,315.315315,175.0,182.0,279.0,213.0,21.0,0.971154,0.131429,0.373626,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,444955.530200,Tampa-St. Petersburg-Clearwater
884091,2023-12-31,440000.0,399949.5,300.469484,317.925225,161.0,160.0,240.0,223.0,29.0,0.968088,0.118012,0.362500,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,446862.962247,Tampa-St. Petersburg-Clearwater

### .head return by default top 5 rows but your can pass argument top(8)

In [30]:
df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta
4,2012-07-31,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,2012,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,Atlanta-Sandy Springs-Alpharetta

### .tail return by default bottom 5 rows and same you can pass paramenter .tail(2)

In [31]:
df.tail(2)

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
884090,2023-11-30,470000.0,425000.0,312.328767,315.315315,175.0,182.0,279.0,213.0,21.0,0.971154,0.131429,0.373626,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,444955.530200,Tampa-St. Petersburg-Clearwater
884091,2023-12-31,440000.0,399949.5,300.469484,317.925225,161.0,160.0,240.0,223.0,29.0,0.968088,0.118012,0.362500,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,446862.962247,Tampa-St. Petersburg-Clearwater

### info return columns details like data types and is there null value etc

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 884092 entries, 0 to 884091
Data columns (total 39 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          884092 non-null  object
 1   median_sale_price             884092 non-null  float64
 2   median_list_price             884092 non-null  float64
 3   median_ppsf                   884092 non-null  float64
 4   median_list_ppsf              884092 non-null  float64
 5   homes_sold                    884092 non-null  float64
 6   pending_sales                 884092 non-null  float64
 7   new_listings                  884092 non-null  float64
 8   inventory                     884092 non-null  float64
 9   median_dom                    884092 non-null  float64
 10  avg_sale_to_list              884092 non-null  float64
 11  sold_above_list               884092 non-null  float64
 12  off_market_in_two_weeks       884092 non-null  float64
 13  city                          884092 non-null  object
 14  zipcode                       884092 non-null  int64
 15  year                          884092 non-null  int64
 16  bank                          884092 non-null  float64
 17  bus                           884092 non-null  float64
 18  hospital                      884092 non-null  float64
 19  mall                          884092 non-null  float64
 20  park                          884092 non-null  float64
 21  restaurant                    884092 non-null  float64
 22  school                        884092 non-null  float64
 23  station                       884092 non-null  float64
 24  supermarket                   884092 non-null  float64
 25  Total Population              884092 non-null  float64
 26  Median Age                    884092 non-null  float64
 27  Per Capita Income             884092 non-null  float64
 28  Total Families Below Poverty  884092 non-null  float64
 29  Total Housing Units           884092 non-null  float64
 30  Median Rent                   884092 non-null  float64
 31  Median Home Value             884092 non-null  float64
 32  Total Labor Force             884092 non-null  float64
 33  Unemployed Population         884092 non-null  float64
 34  Total School Age Population   884092 non-null  float64
 35  Total School Enrollment       884092 non-null  float64
 36  Median Commute Time           884092 non-null  float64
 37  price                         884092 non-null  float64
 38  city_full                     884092 non-null  object
dtypes: float64(34), int64(2), object(3)
memory usage: 263.1+ MB

### describe() shows a quick statistic summary of your data

In [33]:
df.describe()

,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price
count,8.840920e+05,8.840920e+05,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,8.840920e+05,884092.000000,884092.000000,884092.000000,884092.000000,884092.000000,8.840920e+05
mean,3.941026e+05,4.229849e+05,223.068328,231.169836,76.722786,81.471457,92.910352,77.300772,61.289875,0.978253,0.264381,0.305987,48717.657886,2017.577465,13.383858,0.669890,3.506153,1.291738,48.988852,64.992721,48.666562,5.702948,9.717705,21802.545737,36.734335,35253.501303,21457.525088,8714.480844,1146.686284,3.147922e+05,11455.779512,829.769133,20998.337745,20998.337745,9687.919963,3.913289e+05
std,3.815481e+05,1.899201e+06,696.724208,290.120210,76.698331,85.327617,92.695852,89.041772,82.220497,0.063550,0.201862,0.239115,32367.294585,3.413570,31.044991,1.609562,7.367831,2.751646,75.719358,199.436568,62.301837,16.773501,19.202420,19794.373860,12.437231,21555.151881,19554.169658,7588.635086,547.236746,2.672194e+05,10429.516147,954.753745,19008.391216,19008.391216,8841.743137,3.445383e+05
min,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1431.000000,2012.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,1.046432e+04
25%,1.850000e+05,1.990000e+05,110.639667,116.818175,19.000000,17.000000,24.000000,20.000000,26.000000,0.965158,0.120482,0.083333,19038.000000,2015.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,7.000000,0.000000,1.000000,4512.000000,34.100000,23210.000000,4404.000000,1930.000000,852.000000,1.436000e+05,2320.000000,127.000000,4369.000000,4369.000000,1945.000000,1.897063e+05
50%,3.025000e+05,3.200000e+05,166.093929,173.142587,55.000000,57.000000,67.000000,50.000000,45.000000,0.982062,0.223684,0.295455,48029.000000,2018.000000,4.000000,0.000000,1.000000,0.000000,24.000000,13.000000,27.000000,0.000000,4.000000,17848.000000,38.500000,32025.000000,17489.000000,7426.000000,1114.000000,2.501000e+05,9299.000000,538.000000,17247.000000,17247.000000,7830.500000,3.050190e+05
75%,4.800000e+05,4.999000e+05,260.626280,270.181473,111.000000,119.000000,133.000000,103.000000,74.000000,0.998206,0.375000,0.476190,78659.000000,2021.000000,15.000000,1.000000,4.000000,1.000000,63.000000,50.000000,66.000000,4.000000,12.000000,33538.000000,43.100000,44198.000000,32991.000000,13564.000000,1446.000000,4.125000e+05,17702.000000,1192.000000,32290.000000,32290.000000,15013.000000,4.797111e+05
max,2.050000e+07,1.000000e+09,366700.000000,143015.398551,955.000000,1374.000000,1112.000000,1941.000000,7777.000000,1.906250,1.000000,1.000000,98686.000000,2023.000000,447.000000,26.000000,96.000000,45.000000,926.000000,3409.000000,560.000000,192.000000,303.000000,130920.000000,91.200000,465868.000000,130605.000000,48734.000000,3501.000000,2.000001e+06,68735.000000,9735.000000,126948.000000,126948.000000,60956.000000,8.463116e+06

### dtypes also return datatypes of column store data

In [34]:
df.dtypes

date                             object
median_sale_price               float64
median_list_price               float64
median_ppsf                     float64
median_list_ppsf                float64
homes_sold                      float64
pending_sales                   float64
new_listings                    float64
inventory                       float64
median_dom                      float64
avg_sale_to_list                float64
sold_above_list                 float64
off_market_in_two_weeks         float64
city                             object
zipcode                           int64
year                              int64
bank                            float64
bus                             float64
hospital                        float64
mall                            float64
park                            float64
restaurant                      float64
school                          float64
station                         float64
supermarket                     float64
Total Population                float64
Median Age                      float64
Per Capita Income               float64
Total Families Below Poverty    float64
Total Housing Units             float64
Median Rent                     float64
Median Home Value               float64
Total Labor Force               float64
Unemployed Population           float64
Total School Age Population     float64
Total School Enrollment         float64
Median Commute Time             float64
price                           float64
city_full                        object
dtype: object

### shape return number of rows and columns

In [35]:
df.shape

(884092, 39)

### Transposing your data columns into rows

In [36]:
#df.T

### sort_index() sort by an axis

In [37]:
df.sort_index(axis=1)
#df.sort_index(axis=1,ascending=False)

,Median Age,Median Commute Time,Median Home Value,Median Rent,Per Capita Income,Total Families Below Poverty,Total Housing Units,Total Labor Force,Total Population,Total School Age Population,Total School Enrollment,Unemployed Population,avg_sale_to_list,bank,bus,city,city_full,date,homes_sold,hospital,inventory,mall,median_dom,median_list_ppsf,median_list_price,median_ppsf,median_sale_price,new_listings,off_market_in_two_weeks,park,pending_sales,price,restaurant,school,sold_above_list,station,supermarket,year,zipcode
0,36.3,2492.0,279500.0,710.0,33052.0,5811.0,2677.0,3171.0,5811.0,5408.0,5408.0,460.0,0.943662,12.0,2.0,ATL,Atlanta-Sandy Springs-Alpharetta,2012-03-31,14.0,4.0,64.0,1.0,59.5,110.183666,217450.0,31.813674,46550.0,44.0,0.043478,60.0,23.0,200773.999557,45.0,57.0,0.142857,4.0,7.0,2012,30002
1,36.3,2492.0,279500.0,710.0,33052.0,5811.0,2677.0,3171.0,5811.0,5408.0,5408.0,460.0,0.946642,12.0,2.0,ATL,Atlanta-Sandy Springs-Alpharetta,2012-04-30,22.0,4.0,69.0,1.0,89.5,130.528256,245000.0,40.723982,61870.0,56.0,0.034483,60.0,29.0,202421.064584,45.0,57.0,0.090909,4.0,7.0,2012,30002
2,36.3,2492.0,279500.0,710.0,33052.0,5811.0,2677.0,3171.0,5811.0,5408.0,5408.0,460.0,0.955624,12.0,2.0,ATL,Atlanta-Sandy Springs-Alpharetta,2012-05-31,24.0,4.0,60.0,1.0,144.5,119.919216,217450.0,63.913043,125500.0,63.0,0.100000,60.0,40.0,202681.309539,45.0,57.0,0.208333,4.0,7.0,2012,30002
3,36.3,2492.0,279500.0,710.0,33052.0,5811.0,2677.0,3171.0,5811.0,5408.0,5408.0,460.0,0.970608,12.0,2.0,ATL,Atlanta-Sandy Springs-Alpharetta,2012-06-30,34.0,4.0,57.0,1.0,126.0,105.617353,189900.0,81.598080,153000.0,50.0,0.108696,60.0,46.0,202998.603897,45.0,57.0,0.176471,4.0,7.0,2012,30002
4,36.3,2492.0,279500.0,710.0,33052.0,5811.0,2677.0,3171.0,5811.0,5408.0,5408.0,460.0,0.982105,12.0,2.0,ATL,Atlanta-Sandy Springs-Alpharetta,2012-07-31,39.0,3.0,50.0,1.0,80.0,83.921175,154000.0,81.598080,165500.0,42.0,0.102041,60.0,49.0,203781.903446,45.0,57.0,0.256410,4.0,6.0,2012,30002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884087,58.0,13748.0,289300.0,1385.0,43197.0,37238.0,21949.0,17525.0,37838.0,37063.0,37063.0,854.0,0.979446,25.0,0.0,TPA,Tampa-St. Petersburg-Clearwater,2023-08-31,185.0,3.0,132.0,1.0,20.0,322.866706,450000.0,313.553299,438000.0,227.0,0.476190,74.0,189.0,438238.668892,65.0,25.0,0.189189,0.0,17.0,2023,34698
884088,58.0,13748.0,289300.0,1385.0,43197.0,37238.0,21949.0,17525.0,37838.0,37063.0,37063.0,854.0,0.975016,25.0,0.0,TPA,Tampa-St. Petersburg-Clearwater,2023-09-30,192.0,3.0,170.0,1.0,18.0,318.285714,459900.0,314.024277,449950.0,243.0,0.460317,74.0,189.0,440569.503271,65.0,25.0,0.166667,0.0,17.0,2023,34698
884089,58.0,13748.0,289300.0,1385.0,43197.0,37238.0,21949.0,17525.0,37838.0,37063.0,37063.0,854.0,0.971822,25.0,0.0,TPA,Tampa-St. Petersburg-Clearwater,2023-10-31,187.0,3.0,185.0,1.0,21.5,314.374076,449450.0,312.328767,450000.0,264.0,0.416667,74.0,192.0,442965.899354,65.0,25.0,0.122995,0.0,17.0,2023,34698
884090,58.0,13748.0,289300.0,1385.0,43197.0,37238.0,21949.0,17525.0,37838.0,37063.0,37063.0,854.0,0.971154,25.0,0.0,TPA,Tampa-St. Petersburg-Clearwater,2023-11-30,175.0,3.0,213.0,1.0,21.0,315.315315,425000.0,312.328767,470000.0,279.0,0.373626,74.0,182.0,444955.530200,65.0,25.0,0.131429,0.0,17.0,2023,34698
884091,58.0,13748.0,289300.0,1385.0,43197.0,37238.0,21949.0,17525.0,37838.0,37063.0,37063.0,854.0,0.968088,25.0,0.0,TPA,Tampa-St. Petersburg-Clearwater,2023-12-31,161.0,3.0,223.0,1.0,29.0,317.925225,399949.5,300.469484,440000.0,240.0,0.362500,74.0,160.0,446862.962247,65.0,25.0,0.118012,0.0,17.0,2023,34698

### sort by values by = "column name"

In [38]:
df.sort_values(by="bus")

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
884087,2023-08-31,438000.0,450000.0,313.553299,322.866706,185.0,189.0,227.0,132.0,20.0,0.979446,0.189189,0.476190,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,4.382387e+05,Tampa-St. Petersburg-Clearwater
884086,2023-07-31,450000.0,432500.0,317.829457,319.591205,209.0,206.0,232.0,128.0,21.0,0.981136,0.224880,0.485437,TPA,34698,2023,25.0,0.0,3.0,1.0,74.0,65.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,4.346675e+05,Tampa-St. Petersburg-Clearwater
884085,2023-06-30,425000.0,424950.0,306.983240,312.518829,227.0,220.0,236.0,135.0,25.0,0.978208,0.193833,0.472727,TPA,34698,2023,25.0,0.0,3.0,1.0,73.0,64.0,25.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,4.312258e+05,Tampa-St. Petersburg-Clearwater
884084,2023-05-31,420000.0,415000.0,297.520661,316.261880,255.0,258.0,235.0,125.0,21.0,0.973700,0.196078,0.437984,TPA,34698,2023,25.0,0.0,3.0,1.0,71.0,64.0,26.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,4.283532e+05,Tampa-St. Petersburg-Clearwater
884080,2023-01-31,435000.0,399450.0,293.324343,309.319487,165.0,179.0,215.0,161.0,26.5,0.964087,0.121212,0.402235,TPA,34698,2023,25.0,0.0,3.0,1.0,71.0,63.0,26.0,0.0,17.0,37838.0,58.0,43197.0,37238.0,21949.0,1385.0,289300.0,17525.0,854.0,37063.0,37063.0,13748.0,4.223667e+05,Tampa-St. Petersburg-Clearwater
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817016,2019-09-30,2075000.0,1699500.0,1175.016355,1149.155182,76.0,77.0,133.0,73.0,15.5,1.106591,0.723684,0.532468,SF,94114,2019,224.0,26.0,13.0,11.0,270.0,1698.0,234.0,64.0,118.0,34754.0,40.0,105246.0,34593.0,18235.0,2172.0,1359100.0,24673.0,977.0,33419.0,33419.0,20614.0,1.845575e+06,San Francisco-Oakland-Berkeley
817015,2019-08-31,1925000.0,1795000.0,1175.339089,1132.185753,85.0,78.0,77.0,25.0,15.0,1.121952,0.729412,0.564103,SF,94114,2019,223.0,26.0,13.0,11.0,271.0,1663.0,233.0,64.0,118.0,34754.0,40.0,105246.0,34593.0,18235.0,2172.0,1359100.0,24673.0,977.0,33419.0,33419.0,20614.0,1.836364e+06,San Francisco-Oakland-Berkeley
817018,2019-11-30,1817500.0,1681950.0,1227.466941,1128.917836,104.0,122.0,163.0,50.0,17.0,1.081136,0.759615,0.508197,SF,94114,2019,225.0,26.0,15.0,11.0,272.0,1715.0,233.0,63.0,117.0,34754.0,40.0,105246.0,34593.0,18235.0,2172.0,1359100.0,24673.0,977.0,33419.0,33419.0,20614.0,1.863579e+06,San Francisco-Oakland-Berkeley
817019,2019-12-31,1822500.0,1695000.0,1224.527192,1129.693487,114.0,112.0,88.0,23.0,17.0,1.080958,0.719298,0.455357,SF,94114,2019,224.0,26.0,15.0,11.0,272.0,1714.0,233.0,63.0,117.0,34754.0,40.0,105246.0,34593.0,18235.0,2172.0,1359100.0,24673.0,977.0,33419.0,33419.0,20614.0,1.874484e+06,San Francisco-Oakland-Berkeley
817017,2019-10-31,2000000.0,1649500.0,1210.084034,1145.030341,83.0,110.0,159.0,67.0,16.0,1.089370,0.746988,0.527273,SF,94114,2019,225.0,26.0,13.0,11.0,272.0,1704.0,234.0,63.0,117.0,34754.0,40.0,105246.0,34593.0,18235.0,2172.0,1359100.0,24673.0,977.0,33419.0,33419.0,20614.0,1.854091e+06,San Francisco-Oakland-Berkeley

## Selection

### Getitem ([]) passing a single label selects a columns and yields a Series equivalent to df.A

In [39]:
df['bus']

0         2.0
1         2.0
2         2.0
3         2.0
4         2.0
         ...
884087    0.0
884088    0.0
884089    0.0
884090    0.0
884091    0.0
Name: bus, Length: 884092, dtype: float64

### passing a slice : selects matching rows

In [40]:
#it return number of rows df[start:end]
df[0:4]

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta

### Select via the position of the passed integers:

In [41]:
df.iloc[3]

date                                                  2012-06-30
median_sale_price                                       153000.0
median_list_price                                       189900.0
median_ppsf                                             81.59808
median_list_ppsf                                      105.617353
homes_sold                                                  34.0
pending_sales                                               46.0
new_listings                                                50.0
inventory                                                   57.0
median_dom                                                 126.0
avg_sale_to_list                                        0.970608
sold_above_list                                         0.176471
off_market_in_two_weeks                                 0.108696
city                                                         ATL
zipcode                                                    30002
year                                                        2012
bank                                                        12.0
bus                                                          2.0
hospital                                                     4.0
mall                                                         1.0
park                                                        60.0
restaurant                                                  45.0
school                                                      57.0
station                                                      4.0
supermarket                                                  7.0
Total Population                                          5811.0
Median Age                                                  36.3
Per Capita Income                                        33052.0
Total Families Below Poverty                              5811.0
Total Housing Units                                       2677.0
Median Rent                                                710.0
Median Home Value                                       279500.0
Total Labor Force                                         3171.0
Unemployed Population                                      460.0
Total School Age Population                               5408.0
Total School Enrollment                                   5408.0
Median Commute Time                                       2492.0
price                                              202998.603897
city_full                       Atlanta-Sandy Springs-Alpharetta
Name: 3, dtype: object

In [42]:
df.iloc[3:5, 0:2]

         date  median_sale_price
3  2012-06-30           153000.0
4  2012-07-31           165500.0

In [43]:
df.iloc[[1, 2, 4], [0, 2]]

         date  median_list_price
1  2012-04-30           245000.0
2  2012-05-31           217450.0
4  2012-07-31           154000.0

In [44]:
df.iloc[1:3, :]

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta

In [45]:
df.iloc[:, 1:3]

        median_sale_price  median_list_price
0                 46550.0           217450.0
1                 61870.0           245000.0
2                125500.0           217450.0
3                153000.0           189900.0
4                165500.0           154000.0
...                   ...                ...
884087           438000.0           450000.0
884088           449950.0           459900.0
884089           450000.0           449450.0
884090           470000.0           425000.0
884091           440000.0           399949.5

[884092 rows x 2 columns]

In [46]:
df.iloc[1, 1]

np.float64(61870.0)

In [47]:
df.iat[1, 1]

np.float64(61870.0)

### Copy dataframe

In [48]:
df2 = df.copy()